# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_movie_browser_backend_development
  username: <%= Rails.application.credentials.dig(:development, :postgres_username) %>
  password:  <%= Rails.application.credentials.dig(:development, :postgres_password) %>

test:
  <<: *default
  database: react_movie_browser_backend_test

production:
  <<: *default
  database: react_movie_browser_backend_production
  username: react_movie_browser_backend
  password: <%= ENV['REACT_MOVIE_BROWSER_BACKEND_DATABASE_PASSWORD'] %>
